name: Update Version Reference in Matching Repos

on:
  push:
    tags:
      - 'v*'  # Triggers the workflow on any tag starting with "v"

jobs:
  update_repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo A
        uses: actions/checkout@v2

      - name: Extract version from tag
        id: get_version
        run: |
          version="${GITHUB_REF#refs/tags/}"
          echo "version=$version" >> $GITHUB_ENV

      - name: Find Repos with Naming Convention
        id: find_repos
        uses: actions/github-script@v6
        env:
          REPO_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        with:
          script: |
            const namingPattern = /^test\d+$/;
            const octokit = new (require("@octokit/action").Octokit)();
            
            async function findRepos() {
              const repos = [];
              for await (const response of octokit.paginate.iterator(octokit.rest.repos.listForAuthenticatedUser, { visibility: "all" })) {
                repos.push(...response.data.filter(repo => namingPattern.test(repo.name)));
              }
              return repos.map(repo => ({ owner: repo.owner.login, name: repo.name, path: 'sbx/alerts.json' }));
            }

            const matchingRepos = await findRepos();
            console.log("Matching repositories:", matchingRepos);

            return matchingRepos;

      - name: Update JSON files in Matching Repos
        uses: actions/github-script@v6
        env:
          REPO_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        with:
          script: |
            const version = process.env.version;
            const { Octokit } = require("@octokit/action");
            const octokit = new Octokit();
            const repos = ${{ steps.find_repos.outputs.result }};

            async function updateFile(owner, repo, path) {
              const { data: file } = await octokit.rest.repos.getContent({
                owner,
                repo,
                path
              });

              const content = Buffer.from(file.content, 'base64').toString();
              const jsonContent = JSON.parse(content);
              jsonContent.version = version;
              
              const updatedContent = Buffer.from(JSON.stringify(jsonContent, null, 2)).toString('base64');

              await octokit.rest.repos.createOrUpdateFileContents({
                owner,
                repo,
                path,
                message: `Update version to ${version}`,
                content: updatedContent,
                sha: file.sha,
                branch: 'main'
              });
            }

            Promise.all(repos.map(repo => updateFile(repo.owner, repo.name, repo.path)))
              .then(() => console.log("Version updated in matching repos"))
              .catch(error => {
                console.error(error);
                process.exit(1);
              });
